language: c
dist: xenial

script: make

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hTAmhTFV2EokJJc4Bkx6ZA3HyG7PNaMRwRM538PcD0JuukiBDkfNG6tv1Ef0uLCCWi09eiGWtuCEjneRWiGiRsnMDIzzVo7NldeKanSzY5W/ZVJQeb2oew1Ji6U9j6RPEvt4alFjzDeTMDhe/ygqGcHhLq4l5NerN2+bn8Oijq/KIe2hbFqMqt8P412t6qOa1eCPnz1ZyyNHOwpsMxnnyaZlmC8HlDc9FMDdu01YNYhZlzZPNx7FNBfeR29efJNh7KlpTnq5qx6kh3D8R9fGM9EBgHqTujkv9wnQ7L9Lqit0EyF66Cq7qZqXNyQzJ3+BdnaKU3Hx8FxrQgFGHAgg6/TlrT/1n1vbZcRWPsBbfk9C5sdYkaVCWCY923bMIG3tmvWsQz9YCLkGPiczctLmsBmsPIAPzZmDtMB8qypMPfUnn1ymIMMdrG9BaZY/MPY7XgtXT265/i0d3Uw4a3Lo0h9BeEXkys+22JszLBg/9Ke8tNaKxxrLn4k0W135f/MSWEJhE9nIui83mTC2paHORQPyNWdaSvVu8AerHrQUhJsy1oO5R9clP/82ZmO77gWi1IAGTlhM43FRrzknfSxxVaXLrQ7G+R0eksgJhnnGtW9pAXenL34EvfuuZBTR0fy0qpzKENlQPmZqGkLDa1u/T1Sixp66pV4tKti0LzUFMuA=
  file: cutter-deps.tar.gz
